### PR TITLE
[Draft] Upgrade rust-bitcoin dependency to 0.31

### LINKED ISSUE #2745: Bump `rust-bitcoin` to version 0.31
After we upgraded to `rust-bitcoin` 0.30 in #2740, we should look into upgrading to 0.31.0 soon to keep up with the most-recent version. However, this time we should try to coordinate the upgrade with the wider ecosystem, especially BDK (cc @notmandatory), which just recently was unblocked from upgrading as `rust-miniscript` released the upgraded version 11.0 (see https://github.com/bitcoindevkit/bdk/issues/1196).

I think we should release 0.0.119 with `rust-bitcoin` 0.30 and then look to upgrade to 0.31 for the following release.

### PR DESCRIPTION
**Pull request by jirijakes**
Commits do not compile on their own. I guess at the end they will be squashed into one, but for ease of reviewing, I broke them up.

Please let me know what else I forgot and what could be done better and easier for reviewing.

- [X] bump bitcoin dependency to v0.31.2 in all subcrates
- [X] fix compilation errors
- [X] fix new deprecations
- [ ] fix broken tests
- [ ] fix std/no-std

Closes #2745.

### Bech32

v0.31 started to use bech32 v0.10, which is a complete rewrite of the library. This PR keeps using bech32 v0.9.1, it just made it explicit (previously was via rust-bitcoin). Upgrade would require many more changes (`FromBase32` and `u5` were removed). Dependency tree will contain both versions of bech32, but they should not be in conflict since v0.31 uses it only internally.

### Amount type

v0.31 uses `Amount` more often, newly for example in `TxOut`'s value. Since this field is used quite often in rust-lightning, this PR accommodates to it by changing some occurrrences of using `u64` for amount of satoshi into `Amount`. I did not try to change all such cases; I usually set the boundary on public interfaces.

In tests, I used all existing calculations in `u64`, converted to `Amount` only at the end.

### Transaction weight

Calculation of transaction weight in v0.31 was [corrected](https://github.com/rust-bitcoin/rust-bitcoin/pull/2076) and that broke some tests.

### PSBT

`Psbt::extract_tx()` newly checks for using too high a fee rate but requires prevouts. Substituted by `Psbt::extract_tx_unchecked_fee_rate()` which behaves the same as `Psbt::extract_tx()` in v0.30.

### transaction_utils / test_tx_change_edge

<details>
  <summary>Error message</summary>
  <pre><code>

---- util::transaction_utils::tests::test_tx_change_edge stdout ----
thread 'util::transaction_utils::tests::test_tx_change_edge' panicked at lightning/src/util/transaction_utils.rs:235:9:
assertion `left == right` failed
  left: 42
 right: 40

  </code></pre>
</details>

This has something to do with corrected calculation of transaction weight. Have not investigated yet in depth.

### lightning-block-sync

<details>
  <summary>Error message</summary>
  <pre><code>

---- convert::tests::into_txid_from_json_response_with_invalid_hex_data stdout ----
thread 'convert::tests::into_txid_from_json_response_with_invalid_hex_data' panicked at lightning-block-sync/src/convert.rs:610:17:
assertion `left == right` failed
  left: "bad hex string length 64 (expected 6)"
 right: "bad hex string length 6 (expected 64)"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- convert::tests::into_txid_from_json_response_with_invalid_txid_data stdout ----
thread 'convert::tests::into_txid_from_json_response_with_invalid_txid_data' panicked at lightning-block-sync/src/convert.rs:622:17:
assertion `left == right` failed
  left: "bad hex string length 64 (expected 4)"
 right: "bad hex string length 4 (expected 64)"

  </code></pre>
</details>

Bug in hex-conservative in error message of parsing hash types from string. [PR #88](https://github.com/rust-bitcoin/hex-conservative/pull/88) should fix it.

### Fuzz

<details>
  <summary>Error message</summary>
  <pre><code>

---- onion_message::tests::test_no_onion_message_breakage stdout ----
thread 'onion_message::tests::test_no_onion_message_breakage' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some(1)`', src/onion_message.rs:285:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- full_stack::tests::test_no_existing_test_breakage stdout ----
thread 'full_stack::tests::test_no_existing_test_breakage' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some(1)`', src/full_stack.rs:1319:9

---- full_stack::tests::test_gossip_exchange_breakage stdout ----
thread 'full_stack::tests::test_gossip_exchange_breakage' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some(1)`', src/full_stack.rs:1430:9

  </code></pre>
</details>

Have not investigated yet.

### CODE REVIEW

**Comment by jirijakes** [comment]
> Please let us know when you want some rounds of review by leaving a comment!

Yes, I will. Thanks!

File: lightning/src/ln/channel.rs [hunk 1]
```diff
@@ -852,7 +853,7 @@ const COMMITMENT_TX_WEIGHT_PER_HTLC: u64 = 172;
 #[cfg(test)]
 pub const COMMITMENT_TX_WEIGHT_PER_HTLC: u64 = 172;
 
-pub const ANCHOR_OUTPUT_VALUE_SATOSHI: u64 = 330;
+pub const ANCHOR_OUTPUT_VALUE_SATOSHI: Amount = Amount::from_sat(330);
```
[the remark this answers is not in the document]
Comment (jirijakes) [reply lightning/src/ln/channel.rs]: True, that makes sense. I reverted back to `u64`.

File: lightning/src/ln/chan_utils.rs [hunk 2]
```diff
@@ -542,6 +545,13 @@ pub struct HTLCOutputInCommitment {
 	pub transaction_output_index: Option<u32>,
 }
 
+impl HTLCOutputInCommitment {
+	/// Returns value of the HTLC.
+	pub const fn amount(&self) -> Amount {
```
[the remark this answers is not in the document]
Comment (jirijakes) [reply lightning/src/ln/chan_utils.rs]: In the latest version, I named it `to_bitcoin_amount()` but I believe there may be better names. Is there some preference?

- `to_btc_amount()`
- `to_amount()`
- `to_amount_sat()`

**Comment by jirijakes** [comment]
This is ready for review.

I still kept the PR broken into multiple commits that do not compile on their own. This way I can point attention to a few specific changes. I will squash all into one commit after review.

File: lightning/src/ln/chan_utils.rs [hunk 3]
```diff
@@ -1431,17 +1447,17 @@ impl CommitmentTransaction {
...
+	fn internal_build_outputs<T>(keys: &TxCreationKeys, to_broadcaster_value_sat: Amount, to_countersignatory_value_sat: Amount, htlcs_with_aux: &mut Vec<(HTLCOutputInCommitment, T)>, channel_parameters: &DirectedChannelTransactionParameters, broadcaster_funding_key: &PublicKey, countersignatory_funding_key: &PublicKey) -> Result<(Vec<TxOut>, Vec<HTLCOutputInCommitment>), ()> {
 		let countersignatory_pubkeys = channel_parameters.countersignatory_pubkeys();
 		let contest_delay = channel_parameters.contest_delay();
 
 		let mut txouts: Vec<(TxOut, Option<&mut HTLCOutputInCommitment>)> = Vec::new();
 
-		if to_countersignatory_value_sat > 0 {
+		if to_countersignatory_value_sat > Amount::ZERO {
 			let script = if channel_parameters.channel_type_features().supports_anchors_zero_fee_htlc_tx() {
 			    get_to_countersignatory_with_anchors_redeemscript(&countersignatory_pubkeys.payment_point).to_v0_p2wsh()
```
[the remark this answers is not in the document]
Comment (jirijakes) [reply lightning/src/ln/chan_utils.rs]: Done!

File: lightning/src/sign/mod.rs [hunk 4]
```diff
@@ -2495,7 +2505,7 @@ pub fn dyn_sign() {
 #[cfg(ldk_bench)]
 pub mod benches {
 	use crate::sign::{EntropySource, KeysManager};
-	use bitcoin::blockdata::constants::genesis_block;
+	use bitcoin::bloderiveata::constants::genesis_block;
```
[the remark this answers is not in the document]
Comment (jirijakes) [reply lightning/src/sign/mod.rs]: Yes, true. Although, it was fixed in later commits, I corrected it in this one, too.

File: lightning/src/ln/chan_utils.rs [hunk 5]
```diff
@@ -1431,17 +1447,17 @@ impl CommitmentTransaction {
...
 			} else {
-			    Payload::p2wpkh(&BitcoinPublicKey::new(countersignatory_pubkeys.payment_point)).unwrap().script_pubkey()
+				ScriptBuf::new_p2wpkh(&Hash160::hash(&countersignatory_pubkeys.payment_point.serialize()).into())
```
[the remark this answers is not in the document]
Comment (jirijakes) [reply lightning/src/ln/chan_utils.rs:1461]: Mmm, I don't know. While the version with `bitcoin::key::PublicKey` is a bit more understandable in the intent, it is more verbose and requires an `expect()`.

So far I kept it but if you think that it would still be better to use `bitcoin::key::PublicKey`, I will change.

Thanks!

**Comment by jirijakes** [comment]
Addressed tnull's comments and rebased.

File: fuzz/Cargo.toml [hunk 6]
```diff
@@ -21,7 +21,8 @@ stdin_fuzz = []
 lightning = { path = "../lightning", features = ["regex", "hashbrown", "_test_utils"] }
 lightning-invoice = { path = "../lightning-invoice" }
 lightning-rapid-gossip-sync = { path = "../lightning-rapid-gossip-sync" }
-bitcoin = { version = "0.30.2", features = ["secp-lowmemory"] }
+bech32 = "0.9.1"
```
Comment (dunxen) [inline fuzz/Cargo.toml:24]: I believe `bech32@0.10.0` is also fine for `bitcoin@0.31.2`, but I guess we'll bump it with the next PR for `bitcoin@0.32.0`

File: lightning/src/util/transaction_utils.rs [hunk 7]
```diff
@@ -226,30 +226,29 @@ mod tests {
...
 		// Check that we never add dust outputs
-		let mut tx = Transaction { version: 2, lock_time: LockTime::ZERO, input: Vec::new(), output: Vec::new() };
+		let mut tx = Transaction { version: Version::TWO, lock_time: LockTime::ZERO, input: Vec::new(), output: Vec::new() };
 		let orig_wtxid = tx.wtxid();
 		let output_spk = ScriptBuf::new_p2pkh(&PubkeyHash::hash(&[0; 0]));
 		assert_eq!(output_spk.dust_value().to_sat(), 546);
-		// 9 sats isn't enough to pay fee on a dummy transaction...
-		assert_eq!(tx.weight().to_wu(), 40); // ie 10 vbytes
-		assert!(maybe_add_change_output(&mut tx, 9, 0, 250, output_spk.clone()).is_err());
+		assert_eq!(tx.weight().to_wu(), 42); // 3 * (base size = 4 + 1 + 1 + 4 = 10) + (total size = 4 + 2 + 1 + 1 + 4 = 12)
```
Comment (dunxen) [inline lightning/src/util/transaction_utils.rs:233]: We should label the individual terms in the base size and total size calculation comment here for clarity.

**Review by dunxen — COMMENTED** [review]
Looks good! Just some minor comments.

If @TheBlueMatt and @tnull are happy with the changes, I think this can be squashed :)

File: fuzz/Cargo.toml (hunk 6 above)
Comment (jirijakes) [reply fuzz/Cargo.toml:24]: There was no 0.10.0 final release (only beta) and it also contains the complete rewrite. So using 0.10 would not help as it would require to rewrite everything in LDK that uses bech32. That's the main reason for sticking to 0.9, so that LDK does not need to rewrite usage of bech32 yet.

**Comment by jirijakes** [comment]
Addressed @dunxen's comments (thanks!), fixed commit compile check, rebased and finally squashed (commits would not compile on their own).

**Review by dunxen — APPROVED** [review]
LGTM let's see if CI is happy (besides any unrelated stuff). Then I'll let @tnull and @TheBlueMatt take a final look. Not sure if anything needs to get in before this but I doubt it will create anything more than a few simple conflicts.

File: lightning/src/util/transaction_utils.rs [hunk 8]
```diff
@@ -215,41 +215,43 @@ mod tests {
...
 		let orig_wtxid = tx.wtxid();
 		let output_spk = ScriptBuf::new_p2pkh(&PubkeyHash::hash(&[0; 0]));
 		assert_eq!(output_spk.dust_value().to_sat(), 546);
-		// 9 sats isn't enough to pay fee on a dummy transaction...
-		assert_eq!(tx.weight().to_wu(), 40); // ie 10 vbytes
-		assert!(maybe_add_change_output(&mut tx, 9, 0, 250, output_spk.clone()).is_err());
+		// base size = version size + varint[input count] + input size + varint[output count] + output size + lock time size
+		// total size = version size + marker + flag + varint[input count] + input size + varint[output count] + output size + lock time size
+		// weight = 3 * base size + total size = 3 * (4 + 1 + 0 + 1 + 0 + 4) + (4 + 1 + 1 + 1 + 0 + 1 + 0 + 4) = 3 * 10 + 12 = 42
+		assert_eq!(tx.weight().to_wu(), 42);
```
[the remark this answers is not in the document]
Comment (jirijakes) [reply lightning/src/util/transaction_utils.rs:236]: rust-bitcoin changed the way how weight was calculated. Probably the previous version was not accurate: https://github.com/rust-bitcoin/rust-bitcoin/issues/2049

File: lightning/src/util/ser.rs [hunk 9]
```diff
@@ -900,7 +901,7 @@ impl Writeable for Vec<Witness> {
 	fn write<W: Writer>(&self, w: &mut W) -> Result<(), io::Error> {
 		(self.len() as u16).write(w)?;
 		for witness in self {
-			(witness.serialized_len() as u16).write(w)?;
+			(witness.size() as u16).write(w)?;
```
[the remark this answers is not in the document]
Comment (jirijakes) [reply lightning/src/util/ser.rs:904]: `serialized_len()` is method on rust-bitcoin's `Witness` that has been deprecated. `size()` should be used instead (the name aligns with terminology from segwit BIPs).

Maybe you mixed up with `Writeable::serialized_length()`?

https://github.com/rust-bitcoin/rust-bitcoin/blob/acd2c47d792477158f48de43a578a6d2886caed7/bitcoin/src/blockdata/witness.rs#L291-L308
